create: componente Header
sergioothoniel/capstone-m3 pull request #8
Opened 2022-05-12 19:08 UTC by zaquinn

criado componente header

2022-05-12 20:06 UTC, marianabonan requested changes

2022-05-12 20:06 UTC, marianabonan commented on src/components/Header/index.jsx
> +function Header({ childrenLeft, childrenMiddle, childrenRight }) {
no padrão estamos usando const

2022-05-12 20:09 UTC, iasmimd requested changes

2022-05-12 20:09 UTC, iasmimd commented on src/components/Header/index.jsx
> +function Header({ childrenLeft, childrenMiddle, childrenRight }) {
não entendi muito bem o motivo de usar 3 childrens, não seria melhor usar apenas uma, por que você pode adicionar o conteúdo que quiser no header?

2022-05-12 21:26 UTC, sergioothoniel requested changes
Rever o comentado

2022-05-12 22:06 UTC, zaquinn commented on src/components/Header/index.jsx
> +function Header({ childrenLeft, childrenMiddle, childrenRight }) {
então, cada children equivale a um posicionamento no header, esquerda, meio, direita, pq usei grind, então cada children é um possivel grindItem,  foi como testei q dava, mas vou reformular pra deixar só 1 children e aí vai ter q passar meio q um componente todo no header toda vez, pq só vai ter a cor, largura e altura responsiva

2022-05-13 20:47 UTC, iasmimd approved these changes

2022-05-13 21:22 UTC, closed without merging